# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_and_course', '0002_auto_20160719_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_in_courses',
            name='Class',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users_in_courses',
            name='Student',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
