# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 00:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_and_course', '0003_auto_20160719_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_in_courses',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='users_in_courses',
            name='Student',
        ),
    ]
